FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive 

# Install PHP and necessary extensions
RUN apt update && apt upgrade --yes
RUN apt-get update && apt-get install -y \
    curl \
    php8.1 \
    php8.1-fpm \
    php8.1-opcache \
    php8.1-gd \
    php8.1-mysqli \
    php8.1-curl \
    php8.1-mbstring \
    php8.1-xml \
    php8.1-zip \
    php8.1-tokenizer \
    php8.1-ctype \
    php8.1-pdo \
    php8.1-phar \
    php8.1-dom

# Install Symfony CLI
RUN ["/bin/bash", "-c", "curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash"]
RUN apt install symfony-cli -y

WORKDIR /project

# Expose the port Symfony server will run on
EXPOSE 8000

# Start Symfony server
CMD symfony server:start --no-interaction --allow-http --port=8000
